item {
    id: 1
    name: 'bull'
}

item {
    id: 2
    name: 'cattle'
}

item {
    id: 3
    name: 'chicken'
}

item {
    id: 4
    name: 'goat'
}

item {
    id: 5
    name: 'monkey'
}

item {
    id: 6
    name: 'parrot'
}

item {
    id: 7
    name: 'raven'
}

item {
    id: 8
    name: 'sheep'
}

item {
    id: 9
    name: 'sparrow'
}